### ISSUE TITLE
Trending Only Shows Last Post

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#24]
Currently the JS overwrites whatever you created in the document (I am assuming this is what is happening). For example, when receiving the following data:

```
[{
"postID":2,
"image":null,
"username":"d",
"postName":"TestPost",
"postContent":"Some content for the test post",
"likes":1
},
{
"postID":11,
"image":"","
username":"nathan",
"postName":"Test Post 2",
"postContent":"Some content for the test post",
"likes":1}
]
```

It produces the following output:

![image](https://user-images.githubusercontent.com/12765521/78511379-051c0480-7751-11ea-8a63-411d2d4d8e37.png)

**Comment by Nathan-Nesbitt** [comment]
This is also an issue on the feed page.

**Comment by emedema** [comment]
should now be fixed in feed and trending
