### ISSUE TITLE
Only show signup/login when not logged in

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#30]
On the trending page, can we make it so that when the user is logged in it will show their username. Else it will show login & signup.

![image](https://user-images.githubusercontent.com/12765521/78511866-d43dce80-7754-11ea-81f2-a799ccfc831b.png)

**Comment by Nathan-Nesbitt** [comment]
Same for when the user is logged in, it shows:

![image](https://user-images.githubusercontent.com/12765521/78528770-066f2080-7795-11ea-8107-e3bfdeb0215b.png)

**Comment by emedema** [comment]
I think this is working now!
