### ISSUE TITLE
Add required JS to postpage

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#32]
You know this I'm just adding Issues so we can keep track!

![image](https://user-images.githubusercontent.com/12765521/78511886-1b2bc400-7755-11ea-9c9a-cafdb9d495a9.png)

**Comment by emedema** [comment]
This is done! the styling in chrome might be a little weird I'm not sure. My browser is refusing to recognize some of my css (though other browsers are).

**Comment by emedema** [comment]
Actually, this needs you to fix the API for likes

**Comment by Nathan-Nesbitt** [comment]
@emedema What does likes need?

**Comment by emedema** [comment]
likes are coming up as undefined because specific posts and post by specific users don't return the number of likes

**Comment by Nathan-Nesbitt** [comment]
Okay I'll have to update specific posts but users should be fixed now.

**Comment by Nathan-Nesbitt** [comment]
Fixed!
