### ISSUE TITLE
Link Heart Icons to like

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#33]
Currently the posts appear on the main page but you can't add a like to them. It just needs a AJAX call to the API endpoint on click! This will fix a lot of pages!

![image](https://user-images.githubusercontent.com/12765521/78511932-5928e800-7755-11ea-83b3-38de5af4160d.png)

**Comment by emedema** [comment]
This might be working, needs some testing

**Comment by Nathan-Nesbitt** [comment]
Not sure if it is working, what code are you expecting to do this?

**Comment by emedema** [comment]
nathan fixed yay and I put everywhere I think
