### ISSUE TITLE
Redirect from feed to hotfeed

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#38]
Not a big deal but this is kinda clunky. I'd just redirect to the hotfeed once this is submitted, or just disable the button to go to feed if you are not logged in.
![image](https://user-images.githubusercontent.com/12765521/78724158-adf96980-78e1-11ea-9576-7b893ad3c092.png)

**Comment by emedema** [comment]
not more alert now
