### ISSUE TITLE
Likes aren't working 

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [Nathan-Nesbitt/fallr#52]

**Comment by Nathan-Nesbitt** [comment]
![image](https://user-images.githubusercontent.com/12765521/78843189-f9317c00-79b6-11ea-8373-2c144f27c331.png)

Like button doesn't work

**Comment by emedema** [comment]
where is this?

**Comment by Nathan-Nesbitt** [comment]
This is on the search and user pages.

**Comment by emedema** [comment]
Completed
